### ISSUE TITLE
adding custom database clarification

### ISSUE THREAD

**Issue by mrland99** [mmcguffi/pLannotate#42]
Hello,

Thank you for the tool-- I managed to install pLannotate and am now trying to add a custom database. 

I see that we can add a new database to the `.yaml` file, something along the lines of

```
fpbase:
  details:
    compressed: false
    default_type: CDS
    location: Default
  location: Default
  method: diamond
  parameters:
  - -k 0
  - --min-orf 1
  - --matrix BLOSUM90
  - --gapopen 10
  - --gapextend 1
  - --algo ctg
  - --id 75
  - --max-hsps 10
  - --culling-overlap 200
  - --seed-cut .001
  - --comp-based-stats 0
  priority: 1
  version: downloaded 2020-09-02
```

However, I'm not sure what format/files are needed for the custom database. I assume I create some files, and then specify the location above. 

I was hoping to look at the existing databases as an example, but I am having trouble where the `Default` location is storing them.

Any chance you could help clarify and/or point to some examples? 

Thanks,
Max

**Comment by NathanNgu** [comment]
Hi there, I basically figured it out. The best way of configuring a custom database is through the diamond library. 
Use diamond to convert fasta files with protein sequences and labels to diamond databases.
Next, create a csv file with all of the proper labels for a diamond database

`custom:
  details: (github comment note: this is for the csv file)
    compressed: False
    default_type: CDSW
    location: /home/nathan_ngu/micromamba/envs/plannotate/customdb/custom.csv
  location: /home/nathan_ngu/micromamba/envs/plannotate/customdb/  (github comment note: this is for the database file)
  method: diamond
  parameters:
  - -k 0
  - --min-orf 1
  - --matrix BLOSUM90
  - --gapopen 10
  - --gapextend 1
  - --algo ctg
  - --id 50
  - --max-hsps 10
  - --culling-overlap 200
  - --seed-cut .001
  - --comp-based-stats 0
  priority: 2
  version: Release 2024_05`

**Comment by mmcguffi** [comment]
Hi @mrland99, @NathanNgu -- apologies for the lack of documentation around this feature. In truth the code was written in such a way to be theoretically extensible via the yaml system y'all have found, but it is a bit kludgy. I have intentions of revamping it to be more clear and more extensible probably within the next year? But it's unlikely that this will happen immediately

**Comment by NathanNgu** [comment]
Hi @mmcguffi @mrland99,
I built a few functions within a UI to add custom DNA sequences to a custom database.
My command line code and file parsing variables may be different because I had to use Ubuntu via WSL but maybe the steps in this code could guide you.

I keep files for .fasta, .csv, .yaml, and .dmnd in a folder.
Whenever I want to update the custom database, I edit the .fasta file (easy to change) and generate a new .dmnd file from the .fasta file

````
self.cmdlst = [
            'cd /',
            'cd path/to/micromamba/env/goes/here',
            'eval "$(micromamba shell hook --shell bash)"',
            'micromamba activate plannotate',
        ]

def add_entry(self, event):
        if self.checkIDUnique() and self.checkSeq() and self.checkLabel() and self.checkDesc():
            self.add_fasta()
            self.add_csv()
            print("Entry added!")
        else:
            print("Please enter all required fields.")

def add_fasta(self):
        aaseq = self.dna2protein(self.seq.text)
        records = list(SeqIO.parse(self.dbfasta, "fasta"))
        new_record = SeqRecord(Seq(aaseq), id=self.id.text, description=self.desc.text)
        records.append(new_record)
        SeqIO.write(records, self.dbfasta, "fasta")
        self.fasta_to_dmnd()

def fasta_to_dmnd(self):
        # fix the path
        parts = self.dbfasta.split('\\')
        index = parts.index('customdb')
        dbinput = '\\'.join(parts[index:])
        # create the dmnd command
        dmnd = 'diamond makedb --in ' + dbinput + ' -d ' + dbinput[:-6]
        dmnd = dmnd.replace('\\','/')

        commands = self.cmdlst + [str(dmnd)]
        # run the command
        process = subprocess.Popen(['wsl', '-d', 'Ubuntu'], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
        for cc in commands:
            process.stdin.write((cc + '\n').encode())
        process.stdin.close()
        print("Check the folder ___ for the output files.")
````

**Comment by mrland99** [comment]
Hey @mmcguffi @NathanNgu ,

This is really helpful. Thanks for the quick responses too. I'll need a closer look once I have more time, but it seems like this should be enough to get started. 

Will keep you guys updated.

Thanks,
Max

**Comment by mrland99** [comment]
Hey @mmcguffi @NathanNgu,

I've created a `customDB.csv` file and `customDB.dmnd` file. However, when I run pLannotate, it is not able to find any custom annotations. I suspect it is because I am not correctly providing access to the `customDB.dmnd` file. How does it know where to find the file? I don't see it specified anywhere in the .yaml.

```
customDB:
  version: downloaded 2020-09-02
  method: diamond
  location: /home/Software/pLannotate/customdb/customDB.csv
  priority: 1
  parameters:
    - -k 0
    - --min-orf 1
    - --matrix BLOSUM90
    - --gapopen 10
    - --gapextend 1
    - --algo ctg
    - --id 75
    - --max-hsps 10
    - --culling-overlap 200
    - --seed-cut .001
    - --comp-based-stats 0
  details:
    default_type: CDS
    compressed: False
```

Thanks,
Max
